### ISSUE TITLE
[ROS2] Reduce velocity on actions

### ISSUE THREAD

**Issue by taylorkf** [personalrobotics/ada_feeding#58]
Reduce movement speed on feeding actions by setting the max velocity scaling factor. This should likely be accomplished at the MoveTo level by accessing the MoveIt settings.

**Comment by amalnanavati** [comment]
I think this should be added as an optional parameter to the MoveTo behavior (defaults to 1.0), and then every MoveTo tree should also expose that parameter, so that we can set it in the yaml. Similar to how we manage `planner_id`.

For MoveTo trees that have more than one MoveTo behavior (e.g., MoveToMouth), they can potentially expose a separate velocity scaling parameter per MoveTo behavior (e.g., move slower on the final approach to the mouth than on the motion to the staging location).
